//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA
    {
        public int idBoleta { get; set; }
        public Nullable<int> NroOperación { get; set; }
        public Nullable<int> idProducto { get; set; }
        public byte[] Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
